#!/bin/bash

# This preamble is kept separate from the .py file because it is
# difficult to use the pdb debugger without it. See info inside
# ../pdbwrapper/pdbwrapper for details.

caller=$1
shift

#
# We desire NOT to set PYTHONPATH here. We desire to let the .py file
# resolve paths to the modules it depends upon. E.g., do NOT do this:
#
#    export PYTHONPATH="$(dirname $caller)/python:${PYTHONPATH}"
#

# Default the major version:
#
#   Save off PYTHON_PREAMBLE_PYTHON_MAJOR_VERSION into a temporary
#   variable.  Then unset the original
#   PYTHON_PREAMBLE_PYTHON_MAJOR_VERSION variable.  Then, if/when this
#   script executes child processes that, in turn, reuse this same
#   python_preamble_basic script, those child processes can opt to use
#   a _different_ PYTHON_PREAMBLE_PYTHON_MAJOR_VERSION value without
#   interference from the parent processes.
#
python_version=${PYTHON_PREAMBLE_PYTHON_MAJOR_VERSION:-2}
unset PYTHON_PREAMBLE_PYTHON_MAJOR_VERSION

# Allow pdb execution by using PYTHON_PREAMBLE_EXTRA_ARGS here (which
# is empty/not-set by default):
exec /usr/bin/env python${python_version} -u ${PYTHON_PREAMBLE_EXTRA_ARGS} "${caller}.py" "$@"
