#!/bin/bash
# -*-mode: Shell-script; indent-tabs-mode: nil; sh-basic-offset: 2 -*-
export PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES="import%20matplotlib|conda|matplotlib"
# Only install conda, the env, and packages within the env, when
# PYTHON_CONDAENV_INSTALL_CHECK is set to 1. By default, leave it
# unset to avoid 4 seconds of checking logic each time we invoke the
# script:
#
#  export PYTHON_CONDAENV_INSTALL_CHECK=1
# 
exec "$(dirname $0)/../python_condaenv_preamble/python_condaenv_preamble" "$0" "$@"
