#!/bin/bash

echo "$0:$LINENO: ERROR: Do not use this anymore; See explanation in the README.md file"
exit 1

# -*-mode: Shell-script; indent-tabs-mode: nil; sh-basic-offset: 2 -*-
export PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES="from%20bs4%20import%20BeautifulSoup|conda|beautifulsoup4"
# Only install conda, the env, and packages within the env, when
# PYTHON_CONDAENV_PREAMBLE_INSTALL is set to 1. By default, leave it
# unset to avoid 4 seconds of checking logic each time we invoke the
# script:
#
#  PYTHON_CONDAENV_PREAMBLE_INSTALL=1 PYTHON_CONDAENV_PREAMBLE_VERBOSE=1 full_path_to_this_script
#

export PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION=3
export PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES="from%20bs4%20import%20BeautifulSoup|conda|beautifulsoup4 import%20pytz|pip|pytz"

exec "$(dirname $0)/python_condaenv_preamble" "$0" "$@"
